---
- name: Setup Demo in Tower
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files: lab-credentials.secret.yml

  tasks:

    - name: More surcharge if using labs intead of RHPDS
      import_tasks: labs.yml
      when: labs

    - name: Create Job Template for Backup
      tower_job_template:
        name: Backup Network Configurations
        inventory: Workshop Inventory
        project: Workshop Project
        job_type: run
        playbook: network_backup.yml
        credential: Workshop Credential
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_hostname }}"
        state: present

    - name: Create temporary file for extra var definition
      tempfile:
        state: file
        suffix: temp
      register: r_extra_vars

    - name: Write extra var definition   
      copy:
        content: "net_banner: WELCOME TO AUTOMATION"
        dest: "{{ r_extra_vars.path }}"
      delegate_to: localhost
  
    - name: Create Job Template for Banner
      tower_job_template:
        name: Network-Banner
        inventory: Workshop Inventory
        project: Workshop Project
        job_type: run
        playbook: network_banner.yml
        credential: Workshop Credential
        extra_vars_path: "{{ r_extra_vars.path }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_hostname }}"
        state: present
  
    - name: Add Tower Project
      tower_project:
        name: Git Backup
        organization: REDHAT NETWORK ORGANIZATION 
        scm_type: git
        scm_url: https://github.com/automaticdavid/git_backup.git
        scm_branch: master
        scm_delete_on_update: yes
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_hostname }}"
        state: present

    - name: Wait for project sync
      pause: 
        seconds: 90 

    - name: Create Job Template for Git Backup
      tower_job_template:
        name: Git Backup
        inventory: Workshop Inventory
        project: Git Backup
        job_type: run
        playbook: backup_to_git.yml
        credential: Workshop Credential
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_hostname }}"
        state: present

    - name: Additional Tower Settings
      shell: |
         tower-cli config host "{{ tower_hostname }}"
         tower-cli config verify_ssl false
         tower-cli login {{ tower_username }} --password {{ tower_password }}
         tower-cli job_template associate_credential --job-template "Backup Network Configurations" --credential "Tower Credential"
        # tower-cli job_template associate_credential --job-template "Git Backup" --credential "Git Credential"


    - name: Remove temporary setup files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ r_extra_vars.path }}"





    
